### ISSUE TITLE
Create the Search functionality 

### ISSUE THREAD

**Issue by sandraalsayar** [sandraalsayar/bts-contribution-vis#17]
- Search by song - shows that one song (if applicable, meaning contribution is not 0%)
- Search by album - shows all songs of that album (if applicable, meaning contribution is not 0%)
- Search functionality is autofilled with a drop down menu of options available, so if the user types a word, if that word is neither available as a song or an album, no search will happen. Users MUST choose from the drop down menu of suggested options that are available.

For example, if user types in "Tear", it should show the following recomendations:
"Love Yourself: Tear"
"Outro: Tear"
"Tear"
Then user MUST select one, or search wouldn't happen

![image.png](https://images.zenhubusercontent.com/5a67612f4b5806bc2bc3f632/6b782142-01fb-4ece-a297-1d4024c492e1)

**Comment by yogunlusi07** [comment]
Complete

**Comment by sandraalsayar** [comment]
It is not complete. No search actually happens.
