### ISSUE TITLE
Add song names to the left of the song box

### ISSUE THREAD

**Issue by sandraalsayar** [sandraalsayar/bts-contribution-vis#26]
Display song names to the left of the bar.
The code for this is already written but need to move it so that it's on the same line as the bar and also make the song name wrap down instead of keep going on the same line.

**Comment by yogunlusi07** [comment]
This issue will cause the progress bar line to be too crowded, if I carry it out. There's not enough space between the Progress bar and album image on the line as is
![Screen Shot 2020-04-15 at 10 19 41 PM](https://user-images.githubusercontent.com/29104994/79407473-5608d580-7f67-11ea-85c3-36a0cc669975.png)
.

**Comment by jpham197** [comment]
imo we can discard this issue

**Comment by sandraalsayar** [comment]
I like that the song name is on top instead of side.
