### ISSUE TITLE
Style the on-hover of albums cutely

### ISSUE THREAD

**Issue by sandraalsayar** [sandraalsayar/bts-contribution-vis#44]
Right now it's pretty lame. GIVE IT LIIIFFFEEEE!!!!
Anyone can have a go at it but imma try it now and see what i can do.

Things that could be done:
- [ ]  Add a border
- [ ]  Add a background color
- [ ]  Make it animate show/disappear
- [ ]  Add a cute sound when it's hovered on maybe???

**Comment by jpham197** [comment]
Is it possible to move the album details up so it doesn't overlap with the album?
![image](https://user-images.githubusercontent.com/19652588/79642560-24149080-816c-11ea-8b06-bb6be2b76b05.png)
