### ISSUE TITLE
Create and color the BTS member orbits

### ISSUE THREAD

**Issue by sandraalsayar** [sandraalsayar/bts-contribution-vis#5]
- [x] Each member's face plus the group photo (with same outfit)
- [x] Each member's circle should have a color:

RM = Red
Jin = Orange
Suga = Yellow
J-Hope = Green
Jimin = Pink
V = Purple
Jungkook = Blue
BTS = Rainbow

**Comment by sandraalsayar** [comment]
I made the BTS orbit black cause rainbow will not work. It looks good anyways.

**Comment by jpham197** [comment]
LGTM
